[profile.default]
# Source and output directories
src = "contracts"
out = "out"
libs = ["lib"]

# Solidity compiler version aligning with Hardhat config
solc_version = "0.8.28"
# Enable optimizer similarly to Hardhat
optimizer = true
optimizer_runs = 200
via_ir = true

# Monad Testnet configuration
eth_rpc_url = "https://testnet-rpc.monad.xyz"
chain_id = 10143

# Sourcify verifier for contract verification on Monad Explorer
[sourcify]
api_url = "https://sourcify-api-monad.blockvision.org" 